ARG VERSION
FROM python:{{label.VERSION}}

ARG YOUR_NAME
ARG YOUR_EMAIL

LABEL maintainer="{{label.YOUR_NAME}}" email="{{label.YOUR_EMAIL}}"
WORKDIR /opt

COPY requirements.txt requirements.txt
RUN pip install flask>=2.0.0

COPY . .

ARG ODOO_URL
ARG PGADMIN_URL

ENV ODOO_URL={{app_icgroup_url.ODOO_URL}}
ENV PGADMIN_URL={{app_icgroup_url.PGADMIN_URL}}

EXPOSE 8080

CMD ["python", "app.py"]
